--------------------------------------------------------------------------------
VERIFYING QUERY
--------------------------------------------------------------------------------
   FAIL for http://tfb-server:8080
     Caused Exception in TFB
                 This almost certainly means your return value is incorrect,
                 but also that you have found a bug. Please submit an issue
                 including this message: class Database has no attribute 'verify_queries'
     Traceback (most recent call last):
       File "/FrameworkBenchmarks/toolset/benchmark/framework_test.py", line 113, in verify_type
         results = test.verify(base_url)
       File "/FrameworkBenchmarks/toolset/test_types/query/query.py", line 32, in verify
         problems = verify_query_cases(self, cases, url, False)
       File "/FrameworkBenchmarks/toolset/test_types/verifications.py", line 401, in verify_query_cases
         expected_rows, check_updates)
       File "/FrameworkBenchmarks/toolset/test_types/verifications.py", line 419, in verify_queries_count
         queries, rows, rows_updated, margin, trans_failures = databases[self.database.lower()].verify_queries(self.config,
     AttributeError: class Database has no attribute 'verify_queries'
     See https://github.com/TechEmpower/FrameworkBenchmarks/wiki/Project-Information-Framework-Tests-Overview#specific-test-requirements
